[package]
name = "covrus"
version = "0.1.0"
edition = "2021"
authors = ["kaaatsu32329 <kaaatsu32329@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
image = "0.24.0"
rand = "0.8.5"
